node {

    stage('Clone') {
        git branch: 'main', url: 'https://github.com/iam-himabindu/Jenkins.git'
    }

    stage('Init') {
        dir('Day-2/Basic-Files') {
            sh 'terraform init'
        }
    }

    stage('Plan') {
        dir('Day-2/Basic-Files') {
            sh 'terraform plan'
        }
    }
}
